name = "GridapIce"
uuid = "056abfb8-394b-42d6-aa23-e432c0261e7c"
authors = ["Daniel Richards <daniel.richards@monash.edu>"]
version = "1.0.0-DEV"

[deps]
GridapDistributed = "f9701e48-63b3-45aa-9a63-9bc6c271f355"
GridapPETSc = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
GridapSolvers = "6d3209ee-5e3c-4db7-a716-942eb12ed534"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
